commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,6 +48,24 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Node.js setup
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ secrets.node_version }}
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: Build app
+        run: npm run build
+
+      - name: Check dist folder exists
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "dist folder not found."
+            exit 1
+          fi
+
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -57,6 +75,7 @@ jobs:
 
       - name: Upload to S3
         run: aws s3 sync dist s3://funbug --delete
+
 
   test:
     needs: deploy
